version: "3.3"
services:
  mysql:
    image: mysql:latest
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - 3306:3306
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - docker-app
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    ports:
      - 5050:80
    depends_on:
      - mysql
    networks:
      - docker-app
  node-app:
    build: .
    image: node-app
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mysql
    networks:
      - docker-app
volumes:
  mysql_data:
networks:
  docker-app:
    driver: bridge
